In [90]:
import numpy as np
import pandas as pd 
from pandas.api.types import is_numeric_dtype

In [112]:
data = pd.read_csv("./burger_king/burger-king-menu.csv")

In [113]:
data.head()

,Category,Calories,Fat Calories,Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Total Carb (g),Dietary Fiber (g),Sugars (g),Protein (g),Weight Watchers
0,Burgers,660.0,360.0,40.0,12.0,1.5,90.0,980.0,49.0,2.0,11.0,28.0,655.0
1,Burgers,740.0,420.0,46.0,16.0,NaN,115.0,1340.0,50.0,2.0,11.0,32.0,735.0
2,Burgers,790.0,NaN,51.0,17.0,2.0,125.0,1560.0,50.0,2.0,11.0,35.0,783.0
3,Burgers,900.0,520.0,58.0,20.0,3.0,175.0,1050.0,49.0,2.0,11.0,48.0,883.0
4,Burgers,980.0,580.0,64.0,24.0,3.0,195.0,1410.0,50.0,2.0,NaN,52.0,963.0

In [114]:
m = data.isnull().sum()

In [115]:
m

Category             0
Calories             3
Fat Calories         3
Fat (g)              2
Saturated Fat (g)    0
Trans Fat (g)        4
Cholesterol (mg)     3
Sodium (mg)          1
Total Carb (g)       3
Dietary Fiber (g)    2
Sugars (g)           2
Protein (g)          1
Weight Watchers      1
dtype: int64

In [116]:
for n,c in data.items():
    if is_numeric_dtype(c):
        if data[n].isnull().sum():
            print(n,data[n].isnull().sum())

Calories 3
Fat Calories 3
Fat (g) 2
Trans Fat (g) 4
Cholesterol (mg) 3
Sodium (mg) 1
Total Carb (g) 3
Dietary Fiber (g) 2
Sugars (g) 2
Protein (g) 1
Weight Watchers 1

In [117]:
for n, c in data.items():
    if is_numeric_dtype(c):
        if data[n].isnull().sum():
            data[n+"_na"]=pd.isnull(c)
        data[n] = c.fillna(c.median())
    print(n,data[n].isnull().sum())

Category 0
Calories 0
Fat Calories 0
Fat (g) 0
Saturated Fat (g) 0
Trans Fat (g) 0
Cholesterol (mg) 0
Sodium (mg) 0
Total Carb (g) 0
Dietary Fiber (g) 0
Sugars (g) 0
Protein (g) 0
Weight Watchers 0

In [118]:
data

,Category,Calories,Fat Calories,Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Total Carb (g),Dietary Fiber (g),...,Fat Calories_na,Fat (g)_na,Trans Fat (g)_na,Cholesterol (mg)_na,Sodium (mg)_na,Total Carb (g)_na,Dietary Fiber (g)_na,Sugars (g)_na,Protein (g)_na,Weight Watchers_na
0,Burgers,660.0,360.0,40.0,12.0,1.5,90.0,980.0,49.0,2.0,...,False,False,False,False,False,False,False,False,False,False
1,Burgers,740.0,420.0,46.0,16.0,0.0,115.0,1340.0,50.0,2.0,...,False,False,True,False,False,False,False,False,False,False
2,Burgers,790.0,245.0,51.0,17.0,2.0,125.0,1560.0,50.0,2.0,...,True,False,False,False,False,False,False,False,False,False
3,Burgers,900.0,520.0,58.0,20.0,3.0,175.0,1050.0,49.0,2.0,...,False,False,False,False,False,False,False,False,False,False
4,Burgers,980.0,580.0,64.0,24.0,3.0,195.0,1410.0,50.0,2.0,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Breakfast,40.0,0.0,0.0,0.0,0.0,0.0,310.0,11.0,0.0,...,False,False,True,False,False,False,False,False,False,False
73,Breakfast,140.0,140.0,15.0,2.5,0.0,10.0,85.0,1.0,0.0,...,False,False,False,False,False,False,False,False,False,False
74,Breakfast,80.0,70.0,8.0,1.5,0.0,5.0,360.0,2.0,0.0,...,False,False,False,False,False,False,False,False,False,False
75,Breakfast,150.0,140.0,15.0,2.5,0.0,20.0,240.0,3.0,0.0,...,False,False,False,False,False,False,False,False,False,True
76,Breakfast,475.0,60.0,6.0,1.0,0.0,10.0,180.0,8.0,0.0,...,False,False,False,False,False,False,False,False,False,False

In [119]:
print(data["Category"].value_counts())

Breakfast    33
Burgers      26
Chicken      18
Name: Category, dtype: int64

In [120]:
replacing = {"Category" : {"Breakfast" : 1,
                           "Burgers" : 2,
                           "Chicken" : 3}}

In [121]:
data_replace = data.copy()
data_replace.replace(replacing, inplace = True)
data_replace

,Category,Calories,Fat Calories,Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Total Carb (g),Dietary Fiber (g),...,Fat Calories_na,Fat (g)_na,Trans Fat (g)_na,Cholesterol (mg)_na,Sodium (mg)_na,Total Carb (g)_na,Dietary Fiber (g)_na,Sugars (g)_na,Protein (g)_na,Weight Watchers_na
0,2,660.0,360.0,40.0,12.0,1.5,90.0,980.0,49.0,2.0,...,False,False,False,False,False,False,False,False,False,False
1,2,740.0,420.0,46.0,16.0,0.0,115.0,1340.0,50.0,2.0,...,False,False,True,False,False,False,False,False,False,False
2,2,790.0,245.0,51.0,17.0,2.0,125.0,1560.0,50.0,2.0,...,True,False,False,False,False,False,False,False,False,False
3,2,900.0,520.0,58.0,20.0,3.0,175.0,1050.0,49.0,2.0,...,False,False,False,False,False,False,False,False,False,False
4,2,980.0,580.0,64.0,24.0,3.0,195.0,1410.0,50.0,2.0,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,1,40.0,0.0,0.0,0.0,0.0,0.0,310.0,11.0,0.0,...,False,False,True,False,False,False,False,False,False,False
73,1,140.0,140.0,15.0,2.5,0.0,10.0,85.0,1.0,0.0,...,False,False,False,False,False,False,False,False,False,False
74,1,80.0,70.0,8.0,1.5,0.0,5.0,360.0,2.0,0.0,...,False,False,False,False,False,False,False,False,False,False
75,1,150.0,140.0,15.0,2.5,0.0,20.0,240.0,3.0,0.0,...,False,False,False,False,False,False,False,False,False,True
76,1,475.0,60.0,6.0,1.0,0.0,10.0,180.0,8.0,0.0,...,False,False,False,False,False,False,False,False,False,False

In [122]:
X = data_replace.iloc[:,0:8]
y = data_replace.iloc[:,8]

In [135]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.25, random_state=0)

In [136]:
final = {"X train " : X_train,
         "X validation " : X_val, 
         "X test " : X_test,
         "y train " : y_train,
         "y validation " : y_val,
         "y test " : y_test}
for i in final:
    print(f"number of {i} : {len(final.get(i))}")

number of X train  : 39
number of X validation  : 14
number of X test  : 24
number of y train  : 39
number of y validation  : 14
number of y test  : 24

In [137]:
y

0     49.0
1     50.0
2     50.0
3     49.0
4     50.0
      ...
72    11.0
73     1.0
74     2.0
75     3.0
76     8.0
Name: Total Carb (g), Length: 77, dtype: float64

### note : have to solve y train value

In [143]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt


rf = RandomForestRegressor(n_estimators=5)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

trs = rf.score(X_train, y_train)
ts = rf.score(X_test, y_test)
rmse = sqrt(mean_squared_error(y_test, y_pred))

In [144]:
print("training score :", trs)
print("test score :" , ts)
print("root mean squared error :", rmse)

training score : 0.9215763788473456
test score : 0.5857414896665925
root mean squared error : 17.134905894109835